config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :ducks do
    resources :bookings, only: :create
  end
  resources :bookings, except: :create
  get "listings", to: "ducks#listings", as: :listings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :duck
  belongs_to :user

end

app/models/duck.rb
class Duck < ApplicationRecord
  include PgSearch::Model
  has_one_attached :photo
  belongs_to :user
  has_many :bookings
  pg_search_scope :search_by_name_category_description,
    against: [ :name, :category, :description, :address ],
    using: {
      tsearch: { prefix: true }
    }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, :category, :description, :price, :address, presence: true
  # validates :name, uniquenes: { scope: :address,
  #   message: "should not list 2 times the same item" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  has_many :bookings
  has_many :ducks, through: :bookings
  has_many :ducks, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end


  def configure_permitted_parameters

    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[edit update destroy]

  def index
    @bookings = policy_scope(Booking)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @booking = Booking.new
  end

  def create
    @duck = Duck.find(params[:duck_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.duck = @duck
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    @duck = @booking.duck
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def destroy
    authorize @booking
    duck = @booking.duck
    @booking.destroy
    redirect_to duck_path(duck)
  end

  private

  def booking_params
    params[:booking].permit(:starts_at, :ends_at)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/ducks_controller.rb
class DucksController < ApplicationController
  before_action :set_duck, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @ducks = policy_scope(Duck.search_by_name_category_description(params[:query]))

    else
      @ducks = policy_scope(Duck.geocoded)

    end
    sorting
    @markers = @ducks.map do |duck|
       {
         lat: duck.latitude,
         lng: duck.longitude,
         infoWindow: render_to_string(partial: "info_window", locals: { duck: duck })
       }
     end
  end

  def listings
    @ducks = policy_scope(current_user.ducks)

    authorize @ducks
  end

  def show
    @booking = Booking.new
    authorize @duck
  end

  def new
    @duck = Duck.new
    authorize @duck
  end

  def edit
    authorize @duck
  end

  def update
    authorize @duck
    @duck.update(duck_params)
    redirect_to duck_path(@duck)
  end

  def create
    @duck = Duck.new(duck_params)
    @duck.user = current_user

    authorize @duck
    if @duck.save
      redirect_to duck_path(@duck)
    else
      render :new
    end
  end

  def destroy
    authorize @duck
    @duck.destroy
    redirect_to listings_path
  end

  private
  def duck_params
    params.require(:duck).permit(:name, :category, :description, :price, :address, :photo)
  end

  def set_duck
    @duck = Duck.find(params[:id])
  end

  def sorting
  if params[:sorted_by]
      if params[:sorted_by] == 'price'
        print "sorting by price"
        @ducks = @ducks.sort_by { |duck| duck.price}
      elsif params[:sorted_by] == 'name'
        @ducks = @ducks.sort_by { |duck| duck.name}
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :show]
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def show
  #   @user = current_user
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <h1>Hi <%= current_user.username %>!</h1>

  <h2>My bookings</h2>
  <br>
  <div class="flexing-container">
    <div class="duck-cards">
    <% current_user.bookings.each do |booking| %>
      <div class="card-product border">
        <%=link_to booking_path(booking) do %>
          <% if booking.duck.photo.attached? %>
            <%= cl_image_tag booking.duck.photo.key, class: "border" %>
          <% end %>
        <% end %>
        <div class="spaced-between">
          <div class="card-product-infos">
              <h2><%= booking.duck.name %></h2>
              <br>
              <h5><%= booking.duck.category %></h5>
              <br>
              <br>
              <p><%= booking.duck.description %></p>
              <br>
              <br>
              <h6 class="item-flex-end"><%= booking.duck.price %> &euro;</h6>
            </div>
          </div>
      </div>
    <% end %>
  </div>

</div>

app/views/bookings/new.html.erb
<div>
  <h1>THIS IS THE NAME OF THE DUCk</h1>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h2>Booking Confirmation</h2>
  <p>Thank you for your booking, <%= current_user.username %>!</p>
  <div class="row">
    <div class="col-md-8">
      <div class="card-white">
        <div class="d-flex justify-content-between mt-3">
          <p><strong>Your reservation</strong></p>
          <p><%= @booking.duck.name %></p>
        </div>
        <div class="d-flex justify-content-between mt-3">
          <p><strong>Pick Up</strong></p>
          <p><%= @booking.starts_at %></p>
        </div>
        <div class="d-flex justify-content-between mt-3">
          <p><strong>Drop Off</strong></p>
          <p><%= @booking.ends_at %></p>
        </div>
        <div class="d-flex justify-content-between mt-3">
          <p><strong>Pick-up point:</strong></p>
          <p><%= @booking.duck.address %></p>
        </div>
        <div class="d-flex justify-content-between mt-3">
          <p><strong>Topic/Category:</strong></p>
          <p><%= @booking.duck.category %></p>
        </div>
        <div class="button-edit-del">
          <a href="#" class="btn btn-primary w-50" data-toggle="modal" data-target="#exampleModalCenter">Edit</a>
          <div class="divider"></div>
          <a href="#" class="btn btn-danger w-50" data-toggle="modal" data-target="#delModalCenter">Cancel Booking</a>
        </div>
      </div>
    </div>
     <div class="col-md-4">

    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Change your booking</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@duck, @booking] do |f| %>
          <%= f.input :starts_at, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :ends_at, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.button :submit, "Submit", class: "btn btn-primary" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="delModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">You're about to delete your booking</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure?</p>
      </div>
      <div class="modal-footer">
        <%= link_to "Confirm cancellation", booking_path(@booking), class: "btn btn-danger", method: :delete %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/ducks/_info_window.html.erb
<h2><%= duck.name %></h2>
<p><%= duck.address %></p>

app/views/ducks/edit.html.erb
<div class="container">
  <%= simple_form_for([ @user, @duck]) do |form| %>
    <%= form.input :name %>
    <%= form.input :category %>
    <%= form.input :description %>
    <%= form.input :price %>
    <%= form.input :address %>
    <%= form.input :photo, as: :file %>
    <%= form.button :submit, class: "btn btn-success"%>
  <% end %>
</div>

app/views/ducks/index.html.erb
<div class="flexing-container">
  <div class="duck-cards">
    <% @ducks.each do |duck| %>
      <div class="card-product border">
        <%= link_to duck_path(duck) do %>
          <% if duck.photo.attached? %>
            <%= cl_image_tag duck.photo.key%>
          <% end %>
        <% end %>
          <div class="spaced-between">
            <div class="card-product-infos">
              <h2><%= duck.name %></h2>
              <br>
              <h5>Category: <%= duck.category %></h5>
              <br>
              <br>
              <p><%= duck.description %></p>
              <br>
              <br>
              <h6 class="item-flex-end"><%= duck.price %> :&euro;</h6>
            </div>
          </div>
      </div>
    <% end %>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/ducks/listings.html.erb
<div class="container">
  <% @ducks.each do |duck| %>
    <%=link_to duck_path(duck) do %>
    <div class="test remove-underline link-text-black">
      <div class="card-listing">
        <% if duck.photo.attached? %>
          <%= cl_image_tag duck.photo.key, class: "border" %>
        <% end %>
        <div class='card-listing-infos'>
          <h2><%= duck.name %></h2>
          <h2><%= duck.category %></h2>
        </div>
        <div class="card-listing-infos">
          <p><%= duck.description %></p>
          <h6><%= duck.price %> :&euro;</h6>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/ducks/new.html.erb
<div class="container">
  <%= simple_form_for([ @user, @duck]) do |form| %>
    <%= form.input :name %>
    <%= form.input :category %>
    <%= form.input :description %>
    <%= form.input :price %>
    <%= form.input :address %>
    <%= form.input :photo, as: :file %>
    <%= form.button :submit, class: "btn btn-success"%>
  <% end %>

  <%= link_to('Back to home', root_path, class: "btn btn-primary") %>
</div>

app/views/ducks/show.html.erb
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="duck-infos col-md-8">
        <div class="info-title">
          <div class="flexing-container">
            <div class="duck-cards">
              <div class="card-product border">
                <% if @duck.photo.attached? %>
                <%= cl_image_tag @duck.photo.key %>
                  <% end %>
                <div class="spaced-between">
                  <div class="card-product-infos">
                    <h2> <%= @duck.name %></h2>
                    <br>
                    <p> Category: <%= @duck.category %></p>
                    <br>
                    <br>
                    <p> Description: <%= @duck.description %></p>
                    <br>
                    <br>
                    <h6 class="item-flex-end"><%= @duck.price %> :&euro;</h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-status col-md-4">
      <p>Manage your duck:</p>
      <div class="card-booking">
        <% if policy(@duck).update? %>
        <div class="card-policy">
          <%= link_to "edit", edit_duck_path(@duck), class: "btn btn-primary w-50" %>
          <div class="divider"></div>
          <% if @duck.bookings == [] %>
          <%= link_to "delete", duck_path(@duck), method: :delete, class: "btn btn-danger w-50" %>
          <% end %>
        </div>
        <% else %>
        <p id="price">Start from $50 per day</p>
        <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
          Book duck
        </a>
        <div class="collapse" id="collapseExample">
          <div class="card card-body">
            <%= simple_form_for [@duck, @booking] do |f| %>
            <%= f.input :starts_at, as: :string, required: false, input_html: { id: 'range_start' } %>
            <%= f.input :ends_at, as: :string, required: false, input_html: { id: 'range_end' } %>
            <%= f.button :submit, "Submit", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Noto+Sans|Roboto&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Book and get your duck</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>

    <%= render "shared/footer"%>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="landing_page">
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://samurai.ge/wp-content/uploads/2018/02/rubber-duck-debugging.jpg);">
  <div class="container">
    <h1>Le Duckon helps <strong>stuck developers</strong> to <strong> find their duck</strong>!</h1>
    <p>Improve your programming skills and FAQ your duck</p>
    <br>
    <form action="/ducks" accept-charset="UTF-8" method="get" class="search-form-control">
      <div class='search-flex'>
        <input type="text" name="query" id="query" class="form-control" placeholder="Type in duck's name, location or type">
        <input type="submit" name="commit" value="Find your duck" class="btn btn-gradient">
      </div>
    </form>
  </div>
</div>
<h2 class="text-center" style="padding-top: 20px;">How it works</h2>
<div class="container_cards">
  <div class="landing_card">
    <h3>Search for your duck!!</h3>
    <img class="img-crop" src="https://cdn.xl.thumbs.canstockphoto.com/cartoon-duck-in-a-magnifying-glass-clipart_csp7166301.jpg" alt="">
    <p>You can search for location, type, category, behavior, skill... and much more</p>
  </div>
  <div class="landing_card">
    <h3>Book your duck!!</h3>
    <img class="img-crop" src="https://cdn.dribbble.com/users/568278/screenshots/3969812/rubberduck-dribbble.png" alt="">
    <p>Rent the duck that suits you best</p>
  </div>
  <div class="landing_card">
    <h3>FAQ your duck!!</h3>
    <img class="img-crop" src="https://amsterdamduckstore.com/wp-content/uploads/2019/08/Lingerie-Rubber-Ducks-slant-right-Amsterdam-Duck-Store.jpg" alt="">
    <p>Start coding with your favorite debugging duck and ask it as many questions as you like during your renting period. No boundaries!!!</p>
  </div>
</div>
</div>
</div>

app/views/shared/_footer.html.erb
<div class="footer flexing-center">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <div class="footer-copyright-msg">
    2020 Rent-a-Duck Private Limited. All Rights Reserved.
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
    <%= image_tag "http://pngimg.com/uploads/duck/duck_PNG5032.png" %>
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to('My ducks', listings_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('My Bookings', bookings_path, class: "nav-link") %>
        </li>
        <li class="nav-item">
          <%= link_to('Create a Duck', new_duck_path, class: "nav-link") %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached?%>
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src=<%= cl_image_path current_user.photo.key %> />
          <% else %>
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="http://pngimg.com/uploads/duck/duck_PNG5022.png" />
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <div class="username-pg">
              <% if current_user.username.present? %>
                <p>Welcome, <%= current_user.username %>!</p>
              <% else %>
                <%= current_user.email %>
              <% end %>
            </div>
            <%= button_to('Edit Profile', edit_user_registration_path,:method => :get, class: "dropdown-item") %>
            <%= button_to('Logout', destroy_user_session_path,:method => :delete, class: "dropdown-item") %>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to('Signup', new_user_registration_path, class: "nav-link") %>
        </li>
        <li class="nav-item active">
          <%= link_to('Login', new_user_session_path, class: "nav-link") %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search-bar.html.erb
<div class="container">
  <div class="flexing-center height-search">
    <%= simple_form_for :search, url: root_path, method: "GET", html: { class: 'form-inline' } do |f| %>
    <%= f.input :category, input_html: {value: ""} %>
    <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>